# Generated by Django 6.0.7 on 2026-07-21 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_recruitmentauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Set automatically once the outcome is confirmed (Hired/Rejected). A locked application can only be modified by a Super Admin.'),
        ),
        migrations.AddField(
            model_name='application',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
