# Generated by Django 6.0.7 on 2026-07-22 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_application_is_locked_application_locked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='additional_details',
            field=models.TextField(blank=True, help_text='OS version, RAM, etc.'),
        ),
        migrations.AddField(
            model_name='asset',
            name='device_password',
            field=models.CharField(blank=True, help_text='Login password or PIN for the device', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Set autoAssetCategorymatically once the outcome is confirmed (Hired/Rejected). A locked application can only be modified by a Super Admin.'),
        ),
        migrations.CreateModel(
            name='AssetAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('is_still_using', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hrms.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
    ]
