# Generated by Django 6.0.7 on 2026-07-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_assetcategory_asset_additional_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignmenthistory',
            name='assigned_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
