# Generated by Django 6.0.7 on 2026-07-24 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_alter_assetassignmenthistory_assigned_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('body_html', models.TextField(help_text='HTML body. Supported placeholders: {{candidate_name}}, {{job_title}}, {{company_name}}, {{ctc_offered}}, {{offer_date}}, {{joining_date}}.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='If checked, this stage is auto-added to every new JobPipeline.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='notice_period',
            field=models.PositiveIntegerField(default=0, help_text='Notice period, in days.'),
        ),
        migrations.AddField(
            model_name='application',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='interview',
            name='scorecard',
            field=models.JSONField(blank=True, default=dict, help_text='Structured ratings, e.g. {"technical": 4, "communication": 5, "culture": 3}'),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='content',
            field=models.TextField(blank=True, help_text='Final offer content (rendered from the chosen template, then hand-edited).'),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='offers/generated/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Set automatically once the outcome is confirmed (Hired/Rejected). A locked application can only be modified by a Super Admin.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('referral', 'Referral'), ('career_site', 'Career Site')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_round',
            field=models.CharField(blank=True, help_text='Free-text label — kept for cases with no matching JobPipeline stage.', max_length=100),
        ),
        migrations.CreateModel(
            name='JobPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='hrms.jobposting')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_pipelines', to='hrms.recruitmentstage')),
            ],
            options={
                'ordering': ['job', 'order'],
                'unique_together': {('job', 'stage')},
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, help_text="Which stage of the job's own pipeline this interview covers.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='hrms.jobpipeline'),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_letters', to='hrms.offertemplate'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.ForeignKey(blank=True, help_text="Where this candidate currently sits in the job's pipeline.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='hrms.recruitmentstage'),
        ),
    ]
