# Generated by Django 6.0.7 on 2026-07-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_offertemplate_recruitmentstage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Active', max_length=100)),
                ('bereavement_leave', models.FloatField(default=0.0)),
                ('menstrual_leave', models.FloatField(default=0.0)),
                ('sick_leave', models.FloatField(default=0.0)),
                ('earned_leave', models.FloatField(default=0.0)),
                ('casual_leave', models.FloatField(default=0.0)),
                ('comp_off', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
