# Generated by Django 6.0.7 on 2026-07-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_employeeleavebalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleavebalance',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeleavebalance',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employeeleavebalance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employeeleavebalance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='e_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leaves', to='hrms.employee'),
            preserve_default=False,
        ),
    ]
