# Generated by Django 6.0.7 on 2026-08-04 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_remove_employeeleavebalance_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='effective_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_archives', to='hrms.company'),
        ),
    ]
