# Generated by Django 6.0.7 on 2026-08-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_attendancepolicy_effective_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='day_type',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], default='full', max_length=10),
        ),
    ]
