# Generated by Django 6.0.7 on 2026-08-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_alter_leaveapplication_day_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='day_type',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], default='full', max_length=10),
        ),
    ]
