# Generated by Django 6.0.7 on 2026-08-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0012_alter_leaveapplication_day_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancepolicy',
            options={'ordering': ['-effective_from']},
        ),
        migrations.RenameField(
            model_name='attendancepolicy',
            old_name='max_grace_per_month',
            new_name='grace_allowed_count',
        ),
        migrations.RenameField(
            model_name='attendancepolicy',
            old_name='grace_window_minutes',
            new_name='grace_minutes',
        ),
        migrations.RenameField(
            model_name='attendancepolicy',
            old_name='work_end_time',
            new_name='office_end_time',
        ),
        migrations.RenameField(
            model_name='attendancepolicy',
            old_name='work_start_time',
            new_name='office_start_time',
        ),
        migrations.RemoveField(
            model_name='attendancepolicy',
            name='effective_until',
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='effective_from',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='applied_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='applied_grace_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='applied_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_history', to='hrms.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_start_time',
            field=models.TimeField(default='10:00'),
        ),
    ]
