# Generated by Django 6.0.7 on 2026-08-11 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_alter_attendancepolicy_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Employee who referred this candidate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='hrms.employee'),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='Detailed internal notes on why the candidate was not a fit', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.CharField(blank=True, help_text='Reason for rejection (e.g., Salary mismatch, Skill gap)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentstage',
            name='evaluation_criteria',
            field=models.JSONField(blank=True, default=dict, help_text='Define what to grade, e.g. {"Python": 5, "Communication": 5}'),
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer',
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='If True, only HR can see this note')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hrms.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('scorecard_filled', models.JSONField(default=dict, help_text='The actual scores given based on the Stage evaluation_criteria')),
                ('recommendation', models.CharField(choices=[('hire', 'Hire'), ('maybe', 'Maybe'), ('reject', 'Reject')], default='maybe', max_length=20)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_feedbacks', to='hrms.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ManyToManyField(blank=True, help_text='The panel of employees conducting this interview', related_name='interviews_conducted', to='hrms.employee'),
        ),
    ]
