# Generated by Django 6.0.7 on 2026-08-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0015_alter_leaveapplication_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_confirmation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
