# Generated by Django 6.0.7 on 2026-08-12 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_employee_date_of_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveLiveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bereavement_leave', models.FloatField(default=0.0)),
                ('menstrual_leave', models.FloatField(default=0.0)),
                ('sick_leave', models.FloatField(default=0.0)),
                ('earned_leave', models.FloatField(default=0.0)),
                ('casual_leave', models.FloatField(default=0.0)),
                ('comp_off', models.FloatField(default=0.0)),
                ('e_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_balances', to='hrms.employee')),
            ],
        ),
    ]
