# Generated by Django 6.0.7 on 2026-08-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_employeeleavelivebalance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeLeaveLiveBalance',
            new_name='EmployeeLeaveBalanceLive',
        ),
    ]
