# Generated by Django 6.0.7 on 2026-08-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0018_rename_employeeleavelivebalance_employeeleavebalancelive'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default calendar for new employees')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_calendars', to='hrms.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='holiday_calendar',
            field=models.ForeignKey(blank=True, help_text='Assign regional holiday template to this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrms.holidaycalendar'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='hrms.holidaycalendar'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('calendar', 'date', 'name')},
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='company',
        ),
    ]
