# Generated by Django 6.0.7 on 2026-08-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0019_holidaycalendar_alter_holiday_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Residential/Permanent Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.TextField(blank=True, help_text='Name, relationship, and phone number of person to contact in emergency'),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
