# Generated by Django 6.0.7 on 2026-08-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_employee_address_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number associated with the SIM/Device', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sim',
            field=models.CharField(blank=True, help_text='SIM card number or provider details', max_length=100, null=True),
        ),
    ]
