# Generated by Django 6.0.7 on 2026-08-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0021_asset_phone_number_asset_sim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepolicy',
            name='overtime_threshold_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=4, null=True),
        ),
    ]
