# Generated by Django 6.0.7 on 2026-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0022_alter_attendancepolicy_overtime_threshold_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='full_day_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='company',
            name='half_day_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='company',
            name='overtime_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
        ),
    ]
