# Generated by Django 6.0.7 on 2026-08-19 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0023_company_full_day_threshold_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='hrms.assetcategory'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='required_fields',
            field=models.TextField(blank=True, help_text='Comma separated field names to show in the form'),
        ),
    ]
