# Generated by Django 6.0.7 on 2026-08-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0024_asset_category_assetcategory_required_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleavebalance',
            name='status',
        ),
    ]
