# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0025_remove_employeeleavebalance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates if this employee can act as a reporting manager.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, help_text='Select direct reporting manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_manager', 'Pending Manager Approval'), ('pending_hr', 'Pending HR Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendancePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penalty_date', models.DateField()),
                ('reason', models.CharField(default='Late Arrival (Exceeded Grace Period)', max_length=255)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('deduction_days', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('deduction_source', models.CharField(default='CL', max_length=100)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('lwp', 'LWP (No Leave Balance)'), ('waived', 'Waived')], default='applied', max_length=20)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='hrms.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='hrms.employee')),
            ],
            options={
                'ordering': ['-penalty_date', '-created_at'],
            },
        ),
    ]
