# Generated by Django 6.0.7 on 2026-08-22 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0026_employee_is_manager_employee_reporting_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='invoice_document',
            field=models.FileField(blank=True, help_text='Purchase invoice PDF/Image', null=True, upload_to='assets/invoices/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor_contact',
            field=models.CharField(blank=True, help_text='Vendor phone or email', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Vendor/Supplier name', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expiry',
            field=models.DateField(blank=True, help_text='Warranty expiry date', null=True),
        ),
        migrations.AddField(
            model_name='assetassignmenthistory',
            name='assignment_notes',
            field=models.TextField(blank=True, help_text='Notes at time of assignment'),
        ),
        migrations.AddField(
            model_name='assetassignmenthistory',
            name='return_remarks',
            field=models.TextField(blank=True, help_text='Mandatory remarks if not returned in good condition'),
        ),
        migrations.AddField(
            model_name='assetassignmenthistory',
            name='returned_in_good_condition',
            field=models.BooleanField(blank=True, help_text='Was the asset returned in good condition?', null=True),
        ),
        migrations.AddField(
            model_name='attendancepenalty',
            name='employment_type_snapshot',
            field=models.CharField(blank=True, help_text='Employment type at time of penalty (full_time, intern, etc)', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancepenalty',
            name='is_intern_penalty',
            field=models.BooleanField(default=False, help_text='True if this penalty is a direct salary deduction for an intern'),
        ),
        migrations.AddField(
            model_name='attendancepenalty',
            name='salary_deduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For interns: the monetary amount deducted (half-day salary)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='edit_reason',
            field=models.CharField(blank=True, help_text='Reason for the manual edit', max_length=255),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='edited_by',
            field=models.ForeignKey(blank=True, help_text='User who last manually edited this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='edited_on',
            field=models.DateTimeField(blank=True, help_text='When the record was last manually edited', null=True),
        ),
        migrations.AddField(
            model_name='companynotice',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('event', 'Event'), ('update', 'Policy Update')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='companynotice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_stage',
            field=models.CharField(blank=True, choices=[('pre_natal', 'Pre-Natal Leave'), ('post_natal', 'Post-Natal Leave')], help_text='Required for Maternity/Paternity — Pre-Natal or Post-Natal', max_length=20),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, help_text='The reporting manager who approved at Level 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_leave_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='manager_approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='parent_application',
            field=models.ForeignKey(blank=True, help_text='Links to the rejected application this re-application is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reapplications', to='hrms.leaveapplication'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='relationship',
            field=models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('spouse', 'Spouse'), ('other', 'Other')], help_text='Required for Bereavement Leave — specify relation to deceased', max_length=20),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='Expected deadline for approval review (for SLA tracking)', null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Medical certificate (SL), proof for Maternity/Paternity/Bereavement', null=True, upload_to='leave/documents/'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allocation_mode',
            field=models.CharField(choices=[('annual', 'Annual (Lump Sum)'), ('monthly_accrued', 'Monthly Accrued')], default='annual', help_text='Annual: full allocation at start. Monthly: accrued each month (CL/EL).', max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='min_consecutive_days',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum consecutive days required (e.g., SL requires 2 days minimum).', null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_relationship',
            field=models.BooleanField(default=False, help_text='If True, employee must specify relationship (e.g., Bereavement Leave).'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_stage',
            field=models.BooleanField(default=False, help_text='If True, employee must specify Pre-Natal/Post-Natal stage (Maternity/Paternity).'),
        ),
        migrations.AddField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('hr_policy', 'HR Policy'), ('it_policy', 'IT Policy'), ('safety', 'Safety & Compliance'), ('finance', 'Finance'), ('other', 'Other')], default='hr_policy', max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_mandatory',
            field=models.BooleanField(default=True, help_text='Must be acknowledged by all employees'),
        ),
        migrations.AddField(
            model_name='policy',
            name='quiz_data',
            field=models.JSONField(blank=True, default=list, help_text='Quiz questions: [{"question": "...", "type": "mcq"|"true_false", "options": [...], "correct": index_or_bool}]'),
        ),
        migrations.AddField(
            model_name='policyacknowledgement',
            name='acknowledgment_text',
            field=models.TextField(blank=True, default='I acknowledge that I have read and fully understand all terms and conditions of this policy/notice.'),
        ),
        migrations.AddField(
            model_name='policyacknowledgement',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Once acknowledged, record is locked and cannot be changed'),
        ),
        migrations.AddField(
            model_name='policyacknowledgement',
            name='quiz_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policyacknowledgement',
            name='quiz_responses',
            field=models.JSONField(blank=True, default=list, help_text='Employee quiz answers'),
        ),
        migrations.AddField(
            model_name='policyacknowledgement',
            name='quiz_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score on the quiz', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='attendancepenalty',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('lwp', 'LWP (No Leave Balance)'), ('waived', 'Waived'), ('intern_salary', 'Intern Salary Deduction')], default='applied', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('applied', 'Applied'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('hr_approved', 'HR Approved'), ('hr_rejected', 'HR Rejected'), ('cancelled', 'Cancelled'), ('reapplied', 'Re-Applied')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='hrms.leaveapplication')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PayslipDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_downloads', to=settings.AUTH_USER_MODEL)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='hrms.payslip')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyLeaveAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('accrued_amount', models.DecimalField(decimal_places=2, help_text='Amount credited this month (annual/12)', max_digits=5)),
                ('is_credited', models.BooleanField(default=False)),
                ('credited_on', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_accruals', to='hrms.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_accruals', to='hrms.leavetype')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'leave_type', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PunchRegularizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField()),
                ('requested_check_in', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='regularization/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='hrms.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularization_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
    ]
