# Generated by Django 6.0.7 on 2026-08-22 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0027_asset_invoice_document_asset_vendor_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='rejection_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('offer_letter', 'Offer Letter'), ('resume', 'Resume'), ('experience_letter', 'Experience Letter'), ('marksheet', '10th/12th Marksheet'), ('bank_proof', 'Bank Proof'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('education', 'Education Certificate'), ('other', 'Other')], max_length=30),
        ),
    ]
