# Generated by Django 6.0.7 on 2026-08-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0028_employeedocument_rejection_remarks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='employee',
            name='is_finance',
            field=models.BooleanField(default=False, help_text='Designates whether this employee has access to Payroll, Payslips, and Salary Ledgers.'),
        ),
    ]
