# Generated by Django 6.0.7 on 2026-08-24 07:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0029_alter_company_options_employee_is_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavebalancelive',
            name='maternity_leave',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='employeeleavebalancelive',
            name='paternity_leave',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
    ]
