# Generated by Django 5.2.17 on 2026-08-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0031_attendancerecord_is_face_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_mode',
            field=models.CharField(choices=[('office_only', 'In-Office Kiosk Only (Delhi)'), ('remote_field', 'Remote / Field Allowed (Mobile)')], default='office_only', help_text='Office Only: Punch via office tablet at reception. Remote/Field: Can punch via personal phone.', max_length=20),
        ),
    ]
