# Generated by Django 5.2.17 on 2026-09-01 05:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0032_employee_attendance_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='asset',
            name='model_number',
            field=models.CharField(blank=True, help_text='Manufacturer Model Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='additional_details',
            field=models.TextField(blank=True, help_text='RAM, SSD Capacity, Processor, Accessories included'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_on',
            field=models.DateField(blank=True, help_text='Date when current holder received the asset', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='hrms.assetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='device_password',
            field=models.CharField(blank=True, help_text='PIN / Master login password', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Currently assigned employee. Leave empty if stored in office/warehouse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='invoice_document',
            field=models.FileField(blank=True, help_text='Upload scanned tax invoice or procurement bill (PDF/JPG)', null=True, upload_to='assets/invoices/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='e.g., MacBook Pro M3, Dell Latitude 5420', max_length=150),
        ),
        migrations.AlterField(
            model_name='asset',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Associated mobile phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date of procurement', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='remarks',
            field=models.TextField(blank=True, help_text='Internal notes on physical condition, scratches, or upgrades'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Unique hardware serial number / Service tag', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sim',
            field=models.CharField(blank=True, help_text='SIM Provider / ICCID Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('available', 'Available in Warehouse'), ('assigned', 'Issued / In Active Use'), ('under_repair', 'Under Repair'), ('retired', 'Retired / Disposed')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor_contact',
            field=models.CharField(blank=True, help_text='Supplier phone, email, or representative name', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Supplier / Dealer company name', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty_expiry',
            field=models.DateField(blank=True, help_text='Warranty end date for claim tracking', null=True),
        ),
        migrations.AlterField(
            model_name='assetassignmenthistory',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date handover occurred'),
        ),
        migrations.AlterField(
            model_name='assetassignmenthistory',
            name='assignment_notes',
            field=models.TextField(blank=True, help_text='Condition remarks at time of issuance'),
        ),
        migrations.AlterField(
            model_name='assetassignmenthistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_history', to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='assetassignmenthistory',
            name='is_still_using',
            field=models.BooleanField(default=True, help_text='True if asset is currently with this employee'),
        ),
        migrations.AlterField(
            model_name='assetassignmenthistory',
            name='return_remarks',
            field=models.TextField(blank=True, help_text='Mandatory audit notes if returned damaged or parts missing'),
        ),
        migrations.AlterField(
            model_name='assetassignmenthistory',
            name='returned_date',
            field=models.DateField(blank=True, help_text='Date returned to company custody', null=True),
        ),
        migrations.AlterField(
            model_name='assetassignmenthistory',
            name='returned_in_good_condition',
            field=models.BooleanField(blank=True, help_text='True if returned working with no physical damage; False if damaged/defective', null=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='required_fields',
            field=models.TextField(blank=True, help_text='Comma-separated field identifiers to show dynamically on the creation form'),
        ),
    ]
