# Generated by Django 5.2.17 on 2026-09-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0034_employee_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='applicable_marital_status',
            field=models.CharField(choices=[('all', 'All'), ('married', 'Married Only'), ('single', 'Unmarried Only')], default='all', help_text='Marital status eligible for this leave', max_length=15),
        ),
    ]
