# Generated by Django 5.2.17 on 2026-09-12 10:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0035_leavetype_applicable_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOffRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worked_date', models.DateField(help_text='The Sunday or Holiday on which the employee worked')),
                ('holiday_name', models.CharField(blank=True, default='Sunday / Weekly Off', help_text='Name of the holiday or "Sunday / Weekly Off"', max_length=150)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, help_text='Total hours logged on the off-day (updated at checkout)', max_digits=5)),
                ('credits_earned', models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='1.0 for a full day, 0.5 for a half day worked', max_digits=3)),
                ('status', models.CharField(choices=[('available', 'Available'), ('availed', 'Availed'), ('expired', 'Expired')], default='available', max_length=20)),
                ('availed_on_date', models.DateField(blank=True, help_text='The date the employee took this comp off as leave', null=True)),
                ('attendance_record', models.ForeignKey(blank=True, help_text='The attendance record that triggered this credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_off_source', to='hrms.attendancerecord')),
                ('availed_leave_app', models.ForeignKey(blank=True, help_text='The approved LeaveApplication that consumed this credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availed_comp_off', to='hrms.leaveapplication')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_records', to='hrms.employee')),
            ],
            options={
                'verbose_name': 'Comp Off Record',
                'verbose_name_plural': 'Comp Off Records',
                'ordering': ['-worked_date'],
                'unique_together': {('employee', 'worked_date')},
            },
        ),
    ]
