# Generated by Django 5.2.17 on 2026-09-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0036_compoffrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, help_text="Candidate's current city", max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state',
            field=models.CharField(blank=True, help_text="Candidate's current state", max_length=100),
        ),
    ]
