# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_dashboard', '0002_paymentdiscussionthread_paymentexpecteddatehistory_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_ASM_incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('base_RSM_incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Incentive Categories',
            },
        ),
        migrations.CreateModel(
            name='CustomerIncentiveTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_trigger', to='customer_dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='IncentivePaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid_to_asm', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('amount_frozen', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_payout_record', to='customer_dashboard.customervoucherstatus')),
            ],
            options={
                'verbose_name': 'Incentive Payment Status',
            },
        ),
        migrations.CreateModel(
            name='ProductIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asm_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rsm_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('msp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_special_pack', models.BooleanField(default=False)),
                ('pack_size_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='If pack of 5, set 5. If 5kg, set 5.', max_digits=10)),
                ('has_dynamic_price', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='incentive_calculator.incentivecategory')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_config', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIncentiveTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('ASM_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RSM_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product_Incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentive_calculator.productincentive')),
            ],
        ),
    ]
