# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0002_paymentdiscussionthread_paymentexpecteddatehistory_and_more'),
        ('tally_voucher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customervoucherstatus',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_status', to='tally_voucher.voucher'),
        ),
        migrations.AddField(
            model_name='paymentdiscussionthread',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_payment_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdiscussionthread',
            name='solved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_payment_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdiscussionthread',
            name='voucher_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_thread', to='customer_dashboard.customervoucherstatus'),
        ),
        migrations.AddField(
            model_name='paymentexpecteddatehistory',
            name='set_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentexpecteddatehistory',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_date_history', to='customer_dashboard.paymentdiscussionthread'),
        ),
        migrations.AddField(
            model_name='paymentremark',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentremark',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='customer_dashboard.paymentdiscussionthread'),
        ),
        migrations.AddField(
            model_name='paymentticketevent',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentticketevent',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_events', to='customer_dashboard.paymentdiscussionthread'),
        ),
        migrations.AlterUniqueTogether(
            name='customerunit',
            unique_together={('name', 'salesperson')},
        ),
        migrations.AlterUniqueTogether(
            name='customervoucherstatus',
            unique_together={('customer', 'voucher')},
        ),
    ]
