# Generated by Django 5.2.4 on 2025-12-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0003_customervoucherstatus_voucher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='customer_dashboard.customer')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.salesperson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
