# Generated by Django 5.2.4 on 2026-01-05 10:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0004_customerremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit_period_days', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_profile', to='customer_dashboard.customer')),
            ],
        ),
    ]
