# Generated by Django 5.2.4 on 2026-01-05 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0005_customercreditprofile'),
        ('tally_voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVoucherStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=100)),
                ('voucher_category', models.CharField(max_length=100)),
                ('voucher_date', models.DateField()),
                ('voucher_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('unpaid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_fully_paid', models.BooleanField(blank=True, null=True)),
                ('is_partially_paid', models.BooleanField(blank=True, null=True)),
                ('is_unpaid', models.BooleanField(blank=True, null=True)),
                ('credit_days_elapsed', models.PositiveIntegerField(blank=True, null=True)),
                ('is_credit_period_crossed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_statuses', to='customer_dashboard.customer')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_status', to='tally_voucher.voucher')),
            ],
            options={
                'ordering': ['-voucher_date'],
                'unique_together': {('customer', 'voucher')},
            },
        ),
    ]
