# Generated by Django 5.2.4 on 2026-01-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0007_customerfollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervoucherstatus',
            name='claim_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_requests_made', to='customer_dashboard.salesperson'),
        ),
        migrations.AddField(
            model_name='customervoucherstatus',
            name='claim_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='customervoucherstatus',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_vouchers', to='customer_dashboard.salesperson'),
        ),
    ]
