# Generated by Django 5.2.4 on 2026-02-28 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0008_customervoucherstatus_claim_requested_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDiscussionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_status', models.CharField(choices=[('NONE', 'None'), ('RAISED', 'Raised'), ('SOLVED', 'Solved')], default='NONE', max_length=20)),
                ('raised_at', models.DateTimeField(blank=True, null=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_payment_tickets', to=settings.AUTH_USER_MODEL)),
                ('solved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_payment_tickets', to=settings.AUTH_USER_MODEL)),
                ('voucher_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_thread', to='customer_dashboard.customervoucherstatus')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentExpectedDateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_date_history', to='customer_dashboard.paymentdiscussionthread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='customer_dashboard.paymentdiscussionthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RAISED', 'Raised'), ('SOLVED', 'Solved')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_events', to='customer_dashboard.paymentdiscussionthread')),
            ],
            options={
                'ordering': ['performed_at'],
            },
        ),
    ]
