# Generated by Django 5.2.4 on 2026-06-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0009_paymentdiscussionthread_paymentexpecteddatehistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly label for this unit, e.g. 'Sharma Traders'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_units', to='customer_dashboard.salesperson')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'salesperson')},
            },
        ),
        migrations.CreateModel(
            name='CustomerUnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_membership', to='customer_dashboard.customer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='customer_dashboard.customerunit')),
            ],
            options={
                'ordering': ['customer__name'],
            },
        ),
    ]
