# Generated by Django 6.0.7 on 2026-08-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0010_customerunit_customerunitmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercreditprofile',
            name='credit_period_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
