# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('estimated_days', models.PositiveIntegerField(default=0, help_text='Expected number of days order usually stays in this stage')),
                ('is_final_stage', models.BooleanField(default=False, help_text='If this stage is completed, PO will be marked as arrived')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderTrackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_text', models.CharField(blank=True, max_length=255, null=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('arrived_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_fully_arrived', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expected_delivery_days',
            field=models.IntegerField(blank=True, help_text='Number of days expected for delivery after placing a purchase order', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expected_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_average',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_average_three',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_closing',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_gpt',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_nitin',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_outwards',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='minimum_order_quantity',
            field=models.IntegerField(blank=True, help_text='Minimum quantity that must be ordered from the supplier in a single batch', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='total_historical_entries',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailystockdata',
            unique_together={('product', 'date', 'voucher_type', 'inwards_quantity', 'outwards_quantity', 'closing_quantity')},
        ),
        migrations.CreateModel(
            name='PurchaseOrderStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('manual_days_at_stage', models.DecimalField(blank=True, decimal_places=2, help_text='Optional manual duration. If blank, duration is calculated from entered/exited datetime.', max_digits=8, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_logs', to='inventory.purchaseorderstage')),
            ],
            options={
                'ordering': ['entered_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_order_trackings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
