# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseorderstage_purchaseordertrackingitem_and_more'),
        ('tally_voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordertracking',
            name='tally_voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_tracking', to='tally_voucher.voucher'),
        ),
        migrations.AddField(
            model_name='purchaseorderstagelog',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='inventory.purchaseordertracking'),
        ),
        migrations.AddField(
            model_name='purchaseordertrackingitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchaseordertrackingitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseordertracking'),
        ),
        migrations.AddField(
            model_name='purchaseordertrackingitem',
            name='voucher_stock_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_tracking_item', to='tally_voucher.voucherstockitem'),
        ),
    ]
