# Generated by Django 5.2.4 on 2025-09-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchaseordertracking_tally_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_average',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_average_three',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_closing',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_gpt',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_outwards',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='total_historical_entries',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
