# Generated by Django 5.2.4 on 2025-09-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_min_quantity_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity_nitin',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
