# Generated by Django 5.2.4 on 2025-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_min_quantity_nitin'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
