# Generated by Django 5.2.4 on 2025-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expected_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
