# Generated by Django 5.2.4 on 2026-05-22 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_expected_delivery_days_and_more'),
        ('tally_voucher', '0002_voucherrow_unique_voucher_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('estimated_days', models.PositiveIntegerField(default=0, help_text='Expected number of days order usually stays in this stage')),
                ('is_final_stage', models.BooleanField(default=False, help_text='If this stage is completed, PO will be marked as arrived')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_order_trackings', to=settings.AUTH_USER_MODEL)),
                ('tally_voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_tracking', to='tally_voucher.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('manual_days_at_stage', models.DecimalField(blank=True, decimal_places=2, help_text='Optional manual duration. If blank, duration is calculated from entered/exited datetime.', max_digits=8, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_logs', to='inventory.purchaseorderstage')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='inventory.purchaseordertracking')),
            ],
            options={
                'ordering': ['entered_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderTrackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_text', models.CharField(blank=True, max_length=255, null=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('arrived_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_fully_arrived', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseordertracking')),
                ('voucher_stock_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_tracking_item', to='tally_voucher.voucherstockitem')),
            ],
        ),
    ]
