# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_purchaseorderstage_purchaseordertrackingitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_type', models.CharField(max_length=100)),
                ('voucher_number', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=255)),
                ('voucher_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_text', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('godown', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_rows', to='inventory.inventoryitem')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_rows', to='tally_voucher.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherEmiPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=14)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally_voucher.voucherstockitem')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger', models.CharField(max_length=255)),
                ('narration', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tally_voucher.voucher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('voucher', 'ledger', 'narration', 'amount'), name='unique_voucher_row')],
            },
        ),
        migrations.AddConstraint(
            model_name='voucherstockitem',
            constraint=models.UniqueConstraint(fields=('voucher', 'item', 'item_name_text', 'quantity', 'amount', 'godown'), name='unique_stock_item_per_voucher'),
        ),
    ]
