# Generated by Django 5.2.4 on 2026-01-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally_voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voucherrow',
            constraint=models.UniqueConstraint(fields=('voucher', 'ledger', 'narration', 'amount'), name='unique_voucher_row'),
        ),
    ]
