# Generated by Django 5.2.4 on 2026-05-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally_voucher', '0002_voucherrow_unique_voucher_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherEmiPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=14)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally_voucher.voucherstockitem')),
            ],
        ),
    ]
