# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
import proforma_invoice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_dashboard', '0002_paymentdiscussionthread_paymentexpecteddatehistory_and_more'),
        ('inventory', '0002_purchaseorderstage_purchaseordertrackingitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('surface', 'Surface'), ('air', 'Air')], default='surface', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_sheets', to='inventory.inventoryitem')),
            ],
            options={
                'unique_together': {('product', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='CourierChargeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='proforma_invoice.couriercharge')),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The ceiling price. Requests above this are auto-approved.', max_digits=10, null=True)),
                ('has_dynamic_price', models.BooleanField(default=False)),
                ('min_requirement', models.PositiveIntegerField(default=1)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('hsn', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_price', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The ceiling price. Requests above this are auto-approved.', max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='proforma_invoice.productprice')),
            ],
            options={
                'verbose_name': 'Product Price Tier',
                'verbose_name_plural': 'Product Price Tiers',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('validity', models.DateTimeField(default=proforma_invoice.models.validity_default)),
                ('created_by', models.CharField(default='Oblu', max_length=255)),
                ('dispatch_status', models.CharField(choices=[('processing', 'Still Processing'), ('pending', 'Pending'), ('dispatched', 'Dispatched')], default='processing', max_length=20)),
                ('dispatch_requested_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('is_price_altered', models.BooleanField(default=False)),
                ('courier_mode', models.CharField(choices=[('surface', 'Surface'), ('air', 'Air')], default='surface', max_length=10)),
                ('is_converted_to_pi', models.BooleanField(default=False, help_text='Converted-pi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.customer')),
                ('shipping_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_invoices', to='customer_dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CreditPeriodOverdueByPassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_approved_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.customer')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests_made', to=settings.AUTH_USER_MODEL)),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_approvals', to='proforma_invoice.proformainvoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_name_snapshot', models.CharField(blank=True, help_text='customer', max_length=255, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of creation', max_digits=10, null=True)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price requested by user', max_digits=10, null=True)),
                ('current_courier_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Current - courier', max_digits=10)),
                ('requested_courier_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Requested - courier', max_digits=10)),
                ('current_msrp', models.DecimalField(blank=True, decimal_places=2, help_text='Current - MSRP', max_digits=10, null=True)),
                ('stock_requested', models.IntegerField(default=0, help_text='Stock-requested (Integer)')),
                ('made_by', models.CharField(blank=True, help_text='made-by', max_length=255, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proforma_invoice.proformainvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaPriceChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_product_request', models.BooleanField(default=True)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('msrp_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Snapshot of quantity at time of request', null=True)),
                ('requested_courier_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommended_courier_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('courier_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_under_msrp', models.BooleanField(default=False, help_text='True if ANY item in this request is priced below its MSRP')),
                ('accountant_approved', models.BooleanField(default=False)),
                ('superuser_approved', models.BooleanField(default=False)),
                ('is_permitted', models.BooleanField(default=False, help_text='Ticked if this price/customer combo was already approved in the past')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_this_product_price', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_dashboard.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_requests', to='proforma_invoice.proformainvoice')),
                ('product', models.ForeignKey(blank=True, help_text='Only required if is_product_request is True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_price_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_price_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProformaRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='proforma_invoice.proformainvoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaStockShortageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Stock Confirmed'), ('rejected', 'Unavailable')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='proforma_invoice.proformainvoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedPriceMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_approved_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price_at_approval', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
