# Generated by Django 5.2.4 on 2026-05-12 11:16

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0009_paymentdiscussionthread_paymentexpecteddatehistory_and_more'),
        ('inventory', '0008_inventoryitem_expected_delivery_days_and_more'),
        ('proforma_invoice', '0006_proformainvoice_shipping_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformapricechangerequest',
            name='requested_product_prices',
        ),
        migrations.AddField(
            model_name='productprice',
            name='msrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The ceiling price. Requests above this are auto-approved.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productpricetier',
            name='msrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The ceiling price. Requests above this are auto-approved.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='dispatch_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='dispatch_status',
            field=models.CharField(choices=[('processing', 'Still Processing'), ('pending', 'Pending'), ('dispatched', 'Dispatched')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='is_converted_to_pi',
            field=models.BooleanField(default=False, help_text='Converted-pi'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='current_courier_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current - courier', max_digits=10),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='current_msrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current - MSRP', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of creation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, help_text='customer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='made_by',
            field=models.CharField(blank=True, help_text='made-by', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='requested_courier_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Requested - courier', max_digits=10),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='requested_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price requested by user', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='stock_requested',
            field=models.IntegerField(default=0, help_text='Stock-requested (Integer)'),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='accountant_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='courier_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_dashboard.customer'),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='is_permitted',
            field=models.BooleanField(default=False, help_text='Ticked if this price/customer combo was already approved in the past'),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='is_product_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='is_this_product_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='is_under_msrp',
            field=models.BooleanField(default=False, help_text='True if ANY item in this request is priced below its MSRP'),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='msrp_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Only required if is_product_request is True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='recommended_courier_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='recommended_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='requested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='superuser_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProformaRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='proforma_invoice.proformainvoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaStockShortageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortage_details', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Stock Confirmed'), ('rejected', 'Unavailable')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_request', to='proforma_invoice.proformainvoice')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedPriceMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_approved_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price_at_approval', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
