# Generated by Django 6.0.7 on 2026-08-22 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchaseorderstage_purchaseordertracking_and_more'),
        ('proforma_invoice', '0007_remove_proformapricechangerequest_requested_product_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformastockshortagerequest',
            name='shortage_details',
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Snapshot of quantity at time of request', null=True),
        ),
        migrations.AddField(
            model_name='proformastockshortagerequest',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformastockshortagerequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='proformastockshortagerequest',
            name='requested_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proformastockshortagerequest',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='proforma_invoice.proformainvoice'),
        ),
    ]
