# Generated by Django 5.2.3 on 2025-07-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotationitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
