# Generated by Django 5.2.3 on 2025-07-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_alter_quotationitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
