# Generated by Django 5.2.4 on 2025-08-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_product_has_dynamic_pricing_product_min_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.CharField(default='Bhavya', max_length=255),
        ),
    ]
