# Generated by Django 5.2.4 on 2025-09-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_alter_product_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_requirement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
