# Generated by Django 5.2.4 on 2025-09-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_customer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
