# Generated by Django 5.2.4 on 2025-09-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_product_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_dynamic_pricing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='quotations.product')),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
    ]
