# Generated by Django 5.2.4 on 2025-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_product_has_dynamic_pricing_productpricetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_pincode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_zip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.CharField(default='Oblu', max_length=255),
        ),
    ]
