# Generated by Django 5.2.4 on 2025-09-24 07:47

import quotations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0015_quotation_customer_city_quotation_customer_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='validity',
            field=models.DateTimeField(default=quotations.models.validity_default),
        ),
    ]
