# Generated by Django 5.2.4 on 2025-12-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_quotation_is_price_altered_pricechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.JSONField(blank=True, help_text='List of bullet points for product info', null=True),
        ),
    ]
